common = ['add.cpp', 'minus.cpp']
sourcelist1 = ['Hello.cpp'] + common
sourcelist2 = ['AnotherAdd.cpp'] + common
Program(target = 'calc', source = sourcelist1)
Program(target = 'AnotherCalc', source = sourcelist2)
